name: accounting_ledger
description: دفتر الأستاذ المحاسبي
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_riverpod: ^2.4.9
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7
  flutter_local_notifications: ^16.3.0
  dio: ^5.4.0
  pdf: ^3.10.7
  excel: ^4.0.2
  open_file: ^3.3.2
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  speech_to_text: ^6.6.0
  url_launcher: ^6.2.2
  dynamic_color: ^1.6.9
  fl_chart: ^0.66.2
  collection: ^1.18.0
  uuid: ^4.2.1
  share_plus: ^7.2.1
  permission_handler: ^11.3.0
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
